# StaticRender.jl — run the notebook in a clean worker once, capture
# the rendered output HTML for cells we want to FREEZE in the
# extracted file (`:static`) and for `:bond` cells (the widget HTML
# the bond renders the first time — which the @island then keeps
# in sync via the shared signal).
#
# Reactive cells (`:reactive`) are NOT rendered here. They re-compute
# in the browser at runtime, so capturing a server-side snapshot would
# either be misleading or wrong. (Their first paint is generated by
# the WASM @island during hydration with the bond's default value.)

"""
    render_static_outputs(nb, cells; progress = identity) -> Dict{cell.id => String}

Spin up a fresh `NotebookWorker`, run every cell in topological
order, and return a dict of pre-rendered HTML for cells that need
freezing. Worker is stopped before return regardless of failure.

A cell whose execution errored gets its error HTML frozen too — that
matches what the user sees in the IDE and is what they're extracting.
"""
function render_static_outputs(
    nb::Notebook,
    cells::Vector{CellClass};
    progress::Function = identity,
)::Dict{Any, String}
    out = Dict{Any, String}()

    # Wrap classifier results by cell-id for fast lookup.
    kind_for = Dict{Any, Symbol}()
    for c in cells
        kind_for[c.cell.id] = c.kind
    end

    worker = NotebookWorker(; notebook_path=nb.path)
    try
        # Force-run every cell in topo order so all definitions land in
        # the workspace before any frozen render.
        update_topology!(nb)
        order = execution_order(nb)
        n = length(order.runnable)
        for (i, c) in enumerate(order.runnable)
            progress("  [$(i)/$(n)] $(_brief(c))")
            try
                remote_execute_cell!(worker, c)
            catch e
                @warn "extract: cell errored during static render" cell=string(c.id) exception=e
            end
            # Capture output for cells we're freezing.
            kind = get(kind_for, c.id, :static)
            if kind === :static || kind === :bond
                try
                    out[c.id] = render_output_html(c)
                catch e
                    @warn "extract: render_output_html failed" cell=string(c.id) exception=e
                    out[c.id] = ""
                end
            end
        end
    finally
        try stop_worker!(worker) catch; end
    end
    return out
end

_brief(c::Cell) = begin
    s = strip(c.code)
    s = replace(s, '\n' => " ⏎ ")
    length(s) > 60 ? first(s, 57) * "…" : s
end
