baked_at = "2026-04-20T09:41:12.943"
julia_version = "1.12.4"
sessions_version = "0.1.0"
therapy_version = "0.1.0"
wasmtarget_version = "0.1.0"

[islands.ActivityBar]
n_handlers = 2
n_signals = 2
source = "src/components/ActivityBar.jl"
source_sha256 = "226ac458bed3ff806d79ea2d3b1f87a6dccb0bfa4336f7319abdcfae6e45ae66"
wasm_size = 564

[islands.CellView]
n_handlers = 1
n_signals = 4
source = "src/components/CellView.jl"
source_sha256 = "0a78dcf1ffc6359d566297448936bc1cf9c83b2a7b6e4d8924b873e8c3c9339d"
wasm_size = 766

[islands.NotebookIsland]
n_handlers = 0
n_signals = 0
source = "src/components/Notebook.jl"
source_sha256 = "28ba0c7d9f77288759a4eb0c69f547775121fd62ef6f438ce44db57198c82c98"
wasm_size = 70

[islands.NotebookToolbar]
n_handlers = 0
n_signals = 8
source = "src/components/NotebookToolbar.jl"
source_sha256 = "a9e166246aa833f8d318b7d3f174d105e94ac1208ae6494b04fbe81edcc6bf40"
wasm_size = 913

[islands.StatusBar]
n_handlers = 1
n_signals = 3
source = "src/components/StatusBar.jl"
source_sha256 = "5870260c99d2c2671accbb32c131492de35cd91fbbe618da03093e4f5029003d"
wasm_size = 519
